export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const SET_MONTHLY_DATA = 'SET_MONTHLY_DATA';
export const SET_DAILY_DATA = 'SET_DAILY_DATA';
export const SET_OUTAGE_DATA = 'SET_OUTAGE_DATA';
export const SET_ONDEMAND_DATA = 'SET_ONDEMAND_DATA';
export const SET_PERFORMANCE_DATA = 'SET_PERFORMANCE_DATA';